
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.20.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TerminalCurses {
    using Terminal.Gui;
    
    
    public partial class Test1 {
        
        public Test1() {
            InitializeComponent();

            button.Clicked += Button_Clicked;
            textView.Text = "Hello";
        }

        private void Button_Clicked()
        {

            textView.Text ="" + textView.Text + textField.Text + "\n";
            textField.Text = "";
            textView.SetNeedsDisplay();
        }
    }
}
